# These are supported funding model platforms

github: [simien] # Replace with your GitHub username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# patreon: # Replace with your Patreon username
# tidelift: # Replace with your Tidelift username
# community_bridge: # Replace with your Community Bridge username
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# otechie: # Replace with your Otechie username
