# DigitalEnv Repository Settings
# This file documents the recommended repository settings for the DigitalEnv project

repository:
  name: dgtlenv
  description: "Digital Environment Management System for macOS - Optimized for MacBook Pro (Retina, 15-inch, Mid 2015) running macOS 12.7.6 Monterey"
  homepage: "https://www.simienap.com/"
  topics:
    - macos
    - system-optimization
    - development-environment
    - shell-scripts
    - performance-monitoring
    - pdf-conversion
    - docker-optimization
    - cursor-ide
    - homebrew
    - system-health
    - automation
    - devops

features:
  issues: true
  projects: true
  wiki: false
  discussions: true
  packages: false
  pages: false

branches:
  main:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "test"
          - "security"
          - "documentation"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions: null

labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "invalid"
    color: "e4e669"
    description: "Something doesn't look right"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "performance"
    color: "ffa500"
    description: "Performance improvements"
  - name: "security"
    color: "ff0000"
    description: "Security-related issues"
  - name: "macos"
    color: "0066cc"
    description: "macOS-specific issues"
  - name: "docker"
    color: "2496ed"
    description: "Docker-related issues"
  - name: "cursor-ide"
    color: "00d4aa"
    description: "Cursor IDE optimization"
  - name: "pdf-conversion"
    color: "8b4513"
    description: "PDF conversion functionality"
  - name: "monitoring"
    color: "32cd32"
    description: "System monitoring features"

milestones:
  - title: "v1.1.0"
    description: "Performance improvements and bug fixes"
    state: "open"
  - title: "v1.2.0"
    description: "Enhanced monitoring and automation"
    state: "open"
  - title: "v2.0.0"
    description: "Major feature additions and improvements"
    state: "open"

projects:
  - name: "DigitalEnv Roadmap"
    description: "Project roadmap and feature planning"
    visibility: "public"
  - name: "Bug Triage"
    description: "Bug tracking and resolution"
    visibility: "public"

automation:
  auto_merge: false
  delete_branch_on_merge: true
  squash_merge: true
  rebase_merge: false

collaborators:
  - username: "simien"
    permission: "admin"
